name = "panaxtos"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "panaxtos-db"
database_id = "3cd042ec-3e93-41da-8034-26fcdc26d6d9"
